from enum import Enum
from typing import Dict, Union

from pydantic import BaseModel

class ErrorCode(str, Enum):
    REGISTER_INVALID_PASSWORD = "REGISTER_INVALIED_PASSWORD"
    USER_NOT_FOUND = "USER NOT FOUND"
    USER_NOT_ALLOWED = "USER NOT ALLOWED"
    FORBIDDEN = "FORBIDDEN"
    REGISTER_USER_ALREADY_EXISTS = "REGISTER_USER_ALREADY_EXISTS"
    PARAMTER_ALREADY_EXITS = 'PARAMETER ALREADY EXITSF'